### ISSUE TITLE
Port Integration Migration submodule to Drupal 8

### ISSUE THREAD

**Issue by ademarco** [nuvoleweb/integration#29]
### Scope
In the scope of porting the Integration module to Drupal 8 we can start by porting only the submodule "Integration Migrate" first.

The Integration Migrate module only exposes a Migrate plugin to import for the JSON format specified here: https://github.com/nuvoleweb/integration/wiki/1.-Data-exchange-format

### Tasks
- [x] Create a new branch `8.x-1.x`
- [x] Remove all 7 code :)
- [x] Create an empty `Integration` module, it will function just as a placeholder
- [x] Start porting Integration Migrate module placing it under integration/modules/integration_migrate
- [ ] Test migration both via unit tests and Behat

**Comment by haringsrob** [comment]
Gotta add some more tests:
- More field types
- ??
